---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: db-secret
  namespace: default
spec:
  encryptedData:
    password: AgCo/Go3xTnCVvz7+0rN8bMjUXBW80peGz/H+LSeULamF0eymhlYdXRT0oWjLMC+3JYdK01Fc5aEFnNeOjFxQVrmb1YVMsx/42fsq2c5RPyOfTB04R+npkKtRKmVcTK3nmXqLa7TWLcgH/tkSdlI/uLghwrvCSHEDWw7qgpd1h+WL26Tp7ZLpdfrKWvcggDFbwuqDkG6npx63+roOw7M58LzLujhP7OmEDVX4PLDURr4SDMYB0a9zLTr7du3SUUXMNT4YjbuipprTO6yT704mT43sX21icvVuhK7gJyQlDxkJukqdK8elg4v/hVTmwh/uI6kzOak/Ta9Y82Zzjgo7Vo+4JlwDVDLhE4Yhx1tt1GVcqPyaCbg4u8KoHJS4xbBA5i9tZkXp1IktnXGROs1f4QdVfZabCEDQVORjF2xcRD0Db5VFtJvVIcBzMJab21ujvP3+zXKTD6UIa/twKYT7qbyZwhY0r7bOHXGAYKlWU8oC+NZu3c2ahuIB14zF0zNWEDJS7PRAA6dSOqs1siLYUU+HnTeGShX1Zr2Dyl5NwoeBmnkDJqLcbKcIgeN07rPurYkW0UygouxqtXLb7N2kDD64jnDtxrLPS1ygMnJpA6ac5uy+WzAhSwIBOscvLqPdJyMIaaD0jU+AxR114U4UMqlc+Lcm3msV9EKVI5nrzajfeKxsKQlbgFGPsQg+G6jfokCZHn27aV+r947xA==
  template:
    metadata:
      creationTimestamp: null
      name: db-secret
      namespace: default
    type: Opaque
